return {
	corfdrag = {
		acceleration = 0,
		blocking = true,
		brakerate = 0,
		buildangle = 8192,
		buildcostenergy = 300,
		buildcostmetal = 15,
		buildpic = "CORFDRAG.DDS",
		buildtime = 70,
		canattack = false,
		canrepeat = false,
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 -10 0",
		collisionvolumescales = "37 70 37",
		collisionvolumetype = "box",
		crushresistance = 1500,
		description = "Shark's Teeth",
		footprintx = 2,
		footprintz = 2,
		hidedamage = true,
		idleautoheal = 20,
		idletime = 180,
		maxdamage = 2000,
		maxslope = 32,
		minwaterdepth = 1,
		name = "Shark's Teeth",
		objectname = "CORFDRAG",
		repairable = false,
		seismicsignature = 0,
		sightdistance = 1,
		selfDestructCountdown = 0,
		waterline = 3,
		yardmap = "oooo",
		customparams = {
			model_author = "Mr Bob",
			removestop = true,
			removewait = true,
			subfolder = "corebuildings/seautil",
		},
		sfxtypes = {
			pieceexplosiongenerators = {},
		},
	},
}
