-- Widget Custom data and order, order = 0 disabled widget
return {
	allowUserWidgets = true,
	data = {
		AdvPlayersList = {
			alwaysHideSpecs = false,
			collapsable = false,
			cpuText = false,
			customScale = 1,
			expandDown = false,
			expandLeft = true,
			gameFrame = 469,
			lockcameraHideEnemies = true,
			lockcameraLos = true,
			m_pointActive = true,
			m_seespecActive = true,
			m_takeActive = true,
			specListShow = false,
			transitionTime = 0.60000002,
			vsx = 1366,
			vsy = 768,
			widgetPosX = 1165.68848,
			widgetPosY = 0,
			widgetRelRight = 0,
			widgetRight = 1359.63123,
			widgetTop = 68.5112762,
			lastSystemData = {},
			m_active_Table = {
				ally = true,
				chat = false,
				country = true,
				cpuping = true,
				id = false,
				indent = true,
				name = true,
				rank = true,
				resources = true,
				share = true,
				side = false,
				sizedn = true,
				sizeup = true,
				skill = true,
			},
		},
		["Ally Selected Units"] = {
			maxAlpha = 0.44999999,
			selectPlayerUnits = true,
			version = 1.10000002,
			xRelPos = 0.83499998,
			yRelPos = 0.88,
		},
		AllyCursors = {
			showPlayerName = true,
			showSpectatorName = true,
		},
		["Anti Ranges"] = {
			fadeOnCloseup = true,
			showLineGlow2 = false,
		},
		["Auto Group"] = {
			version = "3.031",
			groups = {},
			options = {
				addall = {
					desc = "Existing units will be added to group# when setting autogroup#.",
					name = "Add All",
					type = "bool",
					value = true,
				},
				cleargroups = {
					name = "Clear Auto Groups",
					type = "button",
				},
				groupnumbers = {
					name = "Display Group Numbers",
					type = "bool",
					value = true,
				},
				immediate = {
					desc = "Units built/resurrected/received are added to autogroups immediately instead of waiting them to be idle.",
					name = "Immediate Mode",
					type = "bool",
					value = false,
				},
				loadgroups = {
					desc = "Preserve auto groupings for next game. Unchecking this clears the groups!",
					name = "Preserve Auto Groups",
					type = "bool",
					value = true,
				},
				verbose = {
					name = "Verbose Mode",
					type = "bool",
					value = true,
				},
			},
		},
		["BA LOS colors"] = {
			colorProfile = "greyscale",
			losWithRadarEnabled = true,
		},
		["Bloom Shader"] = {
			basicAlpha = 0.30000001,
			globalBlursizeMult = 1,
			qualityPreset = 1,
		},
		BuildBar = {
			align = 1,
			autoclose = true,
			iconSizeBase = 28,
			offset = 0,
			oldUnitpics = false,
			openByClick = false,
			side = 1,
		},
		["Camera Remember"] = {
			name = "spring",
		},
		["Comblast & Dgun Range"] = {
			hideOnDistantEnemy = true,
		},
		["Commander Name Tags"] = {
			nameScaling = true,
		},
		["Commands FX"] = {
			filterAIteams = true,
			opacity = 1,
		},
		Cursors = {
			cursorSet = "bar",
			defaultCursorSet = "bar",
		},
		CustomFormations2 = {
			maxHungarianUnits = 20,
		},
		["Darken map"] = {
			darkenFeatures = false,
			maps = {},
		},
		["Defense Range"] = {
			enabled = {
				ally = {
					air = false,
					ground = false,
					nuke = false,
					radar = false,
				},
				enemy = {
					air = true,
					ground = true,
					nuke = true,
					radar = false,
				},
			},
		},
		Ecostats = {
			removeDeadOn = false,
			resTextOn = false,
			right = true,
			xRelPos = 1,
			yRelPos = 1,
		},
		EnemySpotter = {
			drawPlatter = true,
			highlightOpacity = 2.29999995,
			renderAllTeamsAsPlayer = false,
			renderAllTeamsAsSpec = false,
			spotterOpacity = 0.16,
			useXrayHighlight = false,
		},
		["Fancy Selected Units"] = {
			baseOpacity = 0.25,
			currentOption = 2,
			showSecondLine = false,
			spotterOpacity = 0.94999999,
			teamcolorOpacity = 0.69999999,
		},
		["First launch setup"] = {
			firsttimesetupDone = true,
		},
		["Health Bars"] = {
			alwaysDrawBarPercentageForComs = true,
			barScale = 1,
			currentOption = 2,
			drawBarPercentage = 0,
		},
		["Ignore List API"] = {},
		["LOS View"] = {
			lastMapDrawMode = "metal",
		},
		["Light Effects"] = {
			enableDeferred = true,
			enableHeatDistortion = true,
			enableNanolaser = true,
			enableThrusters = true,
			globalLifeMult = 0.64999998,
			globalLightMult = 1.29999995,
			globalLightMultLaser = 1.39999998,
			globalRadiusMult = 1.29999995,
			globalRadiusMultLaser = 0.89999998,
			resetted = 1.39999998,
		},
		["Map Info"] = {
			stickToFloor = false,
		},
		Options = {
			cameraTransitionTime = 0.2,
			currentGroupTab = "gfx",
			maxNanoParticles = 4000,
			customPresets = {},
			savedConfig = {
				advmapshading = {
					[1] = "AdvMapShading",
					[2] = 0,
				},
				advmodelshading = {
					[1] = "AdvModelShading",
					[2] = 0,
				},
				advsky = {
					[1] = "AdvSky",
					[2] = 0,
				},
				camera = {
					[1] = "CamMode",
					[2] = 2,
				},
				decals = {
					[1] = "GroundDecals",
					[2] = 0,
				},
				disticon = {
					[1] = "UnitIconDist",
					[2] = 100,
				},
				grassdetail = {
					[1] = "GrassDetail",
					[2] = 0,
				},
				grounddetail = {
					[1] = "GroundDetail",
					[2] = 200,
				},
				guiopacity = {
					[1] = "ui_opacity",
					[2] = 0.20999999,
				},
				hwcursor = {
					[1] = "HardwareCursor",
					[2] = 1,
				},
				normalmapping = {
					[1] = "NormalMapping",
					[2] = 0,
				},
				particles = {
					[1] = "MaxParticles",
					[2] = 12000,
				},
				shadows = {
					[1] = "Shadows",
					[2] = 0,
				},
				sndvolbattle = {
					[1] = "snd_volbattle",
					[2] = 100,
				},
				sndvolmaster = {
					[1] = "snd_volmaster",
					[2] = 60,
				},
				sndvolmusic = {
					[1] = "snd_volmusic",
					[2] = 20,
				},
				sndvolunitreply = {
					[1] = "snd_volunitreply",
					[2] = 100,
				},
				treewind = {
					[1] = "TreeWind",
					[2] = 0,
				},
				vsync = {
					[1] = "VSync",
					[2] = 0,
				},
				water = {
					[1] = "Water",
					[2] = 0,
				},
			},
		},
		Outline = {
			customSize = 1,
			maxOutlineUnits = 750,
		},
		["Passive builders"] = {
			passiveCons = false,
			passiveLabs = false,
			passiveNanos = true,
		},
		["Persistent Build Spacing"] = {
			buildSpacing = {},
		},
		["Player Color Palette"] = {
			randomize = false,
			useSameTeamColors = false,
		},
		["Player-TV"] = {
			playerChangeDelay = 40,
			toggled = false,
		},
		["Red Build/Order Menu"] = {
			drawBigTooltip = false,
			drawPrice = true,
			drawRadaricon = true,
			drawTooltip = true,
			iconScaling = true,
			largePrice = true,
			largeUnitIcons = true,
			oldUnitpics = false,
			playSounds = true,
			shortcutsInfo = false,
			Config = {
				buildmenu = {
					fadetime = 0.14,
					fadetimeOut = 0.09240001,
					iconhoverscale = 0.91000003,
					iconscale = 0.91000003,
					ispreadx = 0,
					ispready = 0,
					isx = 47,
					isy = 47,
					ix = 5,
					iy = 7,
					margin = 5,
					menuname = "buildmenu",
					padding = 3.4196353,
					px = 0,
					py = 319,
					roundedPercentage = 0.2,
					cbackground = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0.20999999,
					},
					cborder = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 1,
					},
					cbuttonbackground = {
						[1] = 0.1,
						[2] = 0.1,
						[3] = 0.1,
						[4] = 1,
					},
					color2 = {
						[1] = 1,
						[2] = 1,
						[3] = 1,
						[4] = 0.0084,
					},
					ctext = {
						[1] = 1,
						[2] = 1,
						[3] = 1,
						[4] = 1,
					},
					dragbutton = {
						[1] = 2,
						[2] = 3,
					},
					tooltip = {
						background = "In CTRL+F11 mode: Hold ÿÿÿmiddle mouse buttonÿÿÿÿ to drag the buildmenu.",
					},
				},
				ordermenu = {
					fadetime = 0.14,
					fadetimeOut = 0.09240001,
					iconhoverscale = 0.93000001,
					iconscale = 0.93000001,
					ispreadx = 0,
					ispready = 0,
					isx = 47,
					isy = 33,
					ix = 5,
					iy = 4,
					margin = 5,
					menuname = "ordermenu",
					padding = 3.4196353,
					px = 0,
					py = 174,
					roundedPercentage = 0.2,
					cbackground = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0.20999999,
					},
					cborder = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 1,
					},
					cbuttonbackground = {
						[1] = 0.1,
						[2] = 0.1,
						[3] = 0.1,
						[4] = 1,
					},
					color2 = {
						[1] = 1,
						[2] = 1,
						[3] = 1,
						[4] = 0.025,
					},
					ctext = {
						[1] = 1,
						[2] = 1,
						[3] = 1,
						[4] = 1,
					},
					dragbutton = {
						[1] = 2,
						[2] = 3,
					},
					tooltip = {
						background = "In CTRL+F11 mode: Hold ÿÿÿmiddle mouse buttonÿÿÿÿ to drag the ordermenu.",
					},
				},
			},
		},
		["Red Console (Battle and autohosts)"] = {
			Config = {
				console = {
					fadedistance = 1.262272,
					fadetime = 0.25,
					filterduplicates = true,
					fontsize = 12.6227198,
					margin = 8.83590412,
					maxage = 30,
					maxlines = 3,
					maxlinesScrollmode = 3,
					minlines = 3,
					noblur = true,
					px = 409.800018,
					py = 38.4000015,
					sx = 546.400024,
					callytext = {
						[1] = 0,
						[2] = 1,
						[3] = 0,
						[4] = 1,
					},
					cbackground = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0,
					},
					cborder = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0,
					},
					cgametext = {
						[1] = 0.40000001,
						[2] = 1,
						[3] = 1,
						[4] = 1,
					},
					cmisctext = {
						[1] = 0.77999997,
						[2] = 0.77999997,
						[3] = 0.77999997,
						[4] = 1,
					},
					cotherallytext = {
						[1] = 1,
						[2] = 0.5,
						[3] = 0.5,
						[4] = 1,
					},
					cothertext = {
						[1] = 1,
						[2] = 1,
						[3] = 1,
						[4] = 1,
					},
					cspectext = {
						[1] = 1,
						[2] = 1,
						[3] = 0,
						[4] = 1,
					},
					dragbutton = {
						[1] = 2,
						[2] = 3,
					},
					tooltip = {
						background = "In CTRL+F11 mode:  Hold ÿÿÿmiddle mouse buttonÿÿÿÿ to drag the console.\
- Press ÿÿÿCTRLÿÿÿÿ while mouse is above the \
console to activate chatlog viewing.\
- Use mousewheel (+hold ÿÿÿSHIFTÿÿÿÿ for speedup)\
 to scroll through the chatlog.",
					},
				},
			},
		},
		["Red Console (In-game chat only)"] = {
			fontsizeMultiplier = 1,
			showBackground2 = true,
			Config = {
				console = {
					fadedistance = 1.262272,
					fadetime = 0.25,
					filterduplicates = true,
					fontsize = 14.5161276,
					margin = 8.83590412,
					maxage = 60,
					maxlines = 6,
					maxlinesScrollmode = 10,
					minlines = 2,
					noblur = true,
					px = 409.800018,
					py = 80.6399994,
					sx = 546.400024,
					callytext = {
						[1] = 0,
						[2] = 1,
						[3] = 0,
						[4] = 1,
					},
					cbackground = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0,
					},
					cborder = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0,
					},
					cgametext = {
						[1] = 0.40000001,
						[2] = 1,
						[3] = 1,
						[4] = 1,
					},
					cmisctext = {
						[1] = 0.77999997,
						[2] = 0.77999997,
						[3] = 0.77999997,
						[4] = 1,
					},
					cotherallytext = {
						[1] = 1,
						[2] = 0.5,
						[3] = 0.5,
						[4] = 1,
					},
					cothertext = {
						[1] = 1,
						[2] = 1,
						[3] = 1,
						[4] = 1,
					},
					cspectext = {
						[1] = 1,
						[2] = 1,
						[3] = 0,
						[4] = 1,
					},
					dragbutton = {
						[1] = 2,
						[2] = 3,
					},
					tooltip = {
						background = "In CTRL+F11 mode:  Hold ÿÿÿmiddle mouse buttonÿÿÿÿ to drag the console.\
- Press ÿÿÿCTRLÿÿÿÿ while mouse is above the \
console to activate chatlog viewing.\
- Use mousewheel (+hold ÿÿÿSHIFTÿÿÿÿ for speedup)\
 to scroll through the chatlog.",
					},
				},
			},
		},
		["Red Minimap"] = {
			Config = {
				minimap = {
					bsx = 15,
					bsy = 15,
					cbordersize = 2.56472635,
					fadedistance = 100,
					fadetime = 0.25,
					px = 0,
					py = 0,
					sx = 176.639999,
					sy = 176.639999,
					cbackground = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0.20999999,
					},
					cborder = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0,
					},
					cmovebackground = {
						[1] = 0,
						[2] = 1,
						[3] = 0,
						[4] = 0.5,
					},
					cmovecolor = {
						[1] = 0.89999998,
						[2] = 0.89999998,
						[3] = 0.89999998,
						[4] = 0.80000001,
					},
					cresizebackground = {
						[1] = 0.89999998,
						[2] = 0.89999998,
						[3] = 0.89999998,
						[4] = 0.5,
					},
					cresizecolor = {
						[1] = 1,
						[2] = 1,
						[3] = 1,
						[4] = 1,
					},
					dragbutton = {
						[1] = 1,
					},
					tooltip = {},
				},
			},
		},
		["Red Tooltip"] = {
			Config = {
				tooltip = {
					fontsize = 10.5,
					margin = 11,
					padding = 3.4196353,
					px = -0.5,
					py = 659,
					sx = 270,
					sy = 75,
					unitCounterEnabled = false,
					cbackground = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0.20999999,
					},
					cborder = {
						[1] = 0,
						[2] = 0,
						[3] = 0,
						[4] = 0.2,
					},
					color2 = {
						[1] = 1,
						[2] = 1,
						[3] = 1,
						[4] = 0.0084,
					},
					dragbutton = {
						[1] = 2,
						[2] = 3,
					},
					tooltip = {
						background = "In CTRL+F11 mode: Hold ÿÿÿmiddle mouse buttonÿÿÿÿ to drag this element.",
					},
				},
			},
		},
		["Selected Units Buttons"] = {
			oldUnitpics = false,
		},
		["Shadow Quality Manager"] = {
			averageFps = 9,
			disableFps = 0,
			maxQuality = 8192,
			minQuality = 2048,
			previousQuality = 8192,
			previousQualityFps = 30,
		},
		SmartSelect = {
			includeBuilders = true,
			includeNanosAsMobile = true,
			selectBuildingsWithMobile = false,
		},
		Snow = {
			autoReduce = true,
			averageFps = 60,
			customParticleMultiplier = 1,
			gameframe = 1097,
			particleStep = 10,
			snowMaps = {
				sacrifice_v1 = false,
				thecoldplace = false,
				xenolithic_v4 = false,
			},
		},
		["Stockpiler (dynamic)"] = {
			MaxStockpile = 10,
		},
		TeamStats = {
			sortAscending = false,
			sortVar = "damageDealt",
			guiData = {
				mainPanel = {
					draggingBorderSize = 7,
					visible = false,
					absSizes = {
						x = {
							length = 669.340027,
							max = 1047.17566,
							min = 318.687805,
						},
						y = {
							length = 460.800018,
							max = 583.679993,
							min = 513.581787,
						},
					},
					relSizes = {
						x = {
							length = 0.49000001,
							max = 0.76660001,
							min = 0.2333,
						},
						y = {
							length = 0.60000002,
							max = 0.75999999,
							min = 0.22,
						},
					},
				},
			},
		},
		Tombstones = {
			gameframe = 1097,
			tombstones = {},
		},
		["Top Bar"] = {
			resourcebarBgTint = true,
		},
		["Under construction gfx"] = {
			highlightAlpha = 0.40000001,
			useHighlightShader = true,
		},
		["Voice Notifs"] = {
			playTrackedPlayerNotifs = true,
			volume = 1,
			soundList = {
				GamePause = true,
				GameStarted = true,
				IdleBuilder = true,
				NukeLaunched = true,
				PlayerLeft = true,
				UnitLost = true,
				UnitsReceived = true,
				aCommLost = true,
				eCommDestroyed = true,
			},
		},
		["Widget Selector"] = {
			curMaxEntries = 25,
			show = false,
			startEntry = 164,
		},
	},
	order = {
		AdvPlayersList = 30,
		["AdvPlayersList info"] = 29,
		["AdvPlayersList mascotte"] = 0,
		["Air Factory Fly by Default"] = 0,
		["Air ground area attack"] = 0,
		["Ally Selected Units"] = 24,
		AllyCursors = 33,
		["Alternate Chat Keys"] = 34,
		["Anti Ranges"] = 100,
		["Area Mex"] = 35,
		["Area unload"] = 36,
		["Assist Units Maneuver"] = 0,
		["Attack AoE"] = 89,
		["Attack and Move Notification"] = 37,
		["Attack no ally"] = 38,
		["Auto Cloak Popups"] = 0,
		["Auto First Build Facing"] = 39,
		["Auto Group"] = 40,
		["Auto Skirm"] = 0,
		["AutoRepair v0.6"] = 0,
		Autoquit = 41,
		["BA Hotkeys"] = 90,
		["BA Hotkeys -- swap YZ"] = 0,
		["BA LOS colors"] = 42,
		["BA cmdcolors"] = 15,
		["Blast Radius"] = 43,
		["Bloom Shader"] = 28,
		["Bomber control"] = 101,
		["Build Split"] = 44,
		BuildBar = 45,
		BuildETA = 27,
		["Camera Remember"] = 46,
		CameraFlip = 47,
		CameraShake = 0,
		["Changelog Info"] = 7,
		["Clearmapmarks button"] = 30,
		["Clever gathering point"] = 0,
		["Cloak Fire State 2"] = 32,
		CloseFight = 0,
		["Com DontBreakCloak"] = 48,
		["Comblast & Dgun Range"] = 49,
		["Combo Overhead/Free Camera (experimental)"] = 0,
		CommandInsert = 102,
		["Commander Hurt Vignette"] = 111,
		["Commander Name Tags"] = 95,
		["Commands FX"] = 96,
		["Commands info"] = 8,
		["Constructor locater"] = 0,
		["Context Build"] = 91,
		Cursors = 92,
		CustomFormations2 = 115,
		["DGun Stall Assist"] = 0,
		["DGun no ally"] = 50,
		["DGun no ground enemies"] = 0,
		["Darken map"] = 116,
		["Default Group Recall Fix"] = 114,
		["Defense Range"] = 12345,
		["Deferred rendering"] = 12345,
		["Depth of Field"] = 0,
		["Disable Bad Widgets"] = 12345,
		["Discord icon"] = 31,
		["Display DPS"] = 0,
		DontMove = 51,
		["EMP + decloak range"] = 52,
		["Easy Facing"] = 53,
		Ecostats = 93,
		EnemySpotter = 103,
		["Faction Change"] = 16,
		["Factory Auto-Repeat"] = 0,
		["Factory hold position"] = 0,
		FactoryGuard = 0,
		["FactoryQ Manager"] = 0,
		["Fancy Selected Units"] = 18,
		["First launch setup"] = 12345,
		["Frontline Repairs"] = 0,
		["GUI-Shader"] = 0,
		["Game info"] = 97,
		GameTypeInfo = 57,
		["Ghost Radar"] = 54,
		["Ghost Site"] = 55,
		["Given Units"] = 19,
		Grabinput = 0,
		["Group Label"] = 0,
		["Health Bars"] = 25,
		["Highlight Geos"] = 56,
		["Highlight Selected Units"] = 0,
		["Highlight Unit"] = 104,
		["Holdfire Fix"] = 57,
		IceUI = 0,
		["Idle Builders"] = 0,
		["Ignore List API"] = 58,
		ImmobileBuilder = 59,
		["Keybind/Mouse Info"] = 9,
		["Krow Setup"] = 0,
		["LOS View"] = 60,
		["Light Effects"] = 61,
		["Load Own Moving"] = 62,
		["Local Mexes"] = 0,
		["Loop Select"] = 63,
		["Losses Counter "] = 0,
		["Lua UiKeys loader"] = 0,
		Lups = 113,
		["Map Draw Blocker"] = 0,
		["Map Edge Extension"] = 0,
		["Map External VR Grid"] = 0,
		["Map Info"] = 26,
		["Mapmarks FX"] = 98,
		["Metalspot Finder"] = 12345,
		["Mex Snap"] = 64,
		["MexUpg Helper"] = 16,
		["Mouse Buildspacing"] = 112,
		["Mouse FX"] = 99,
		["Mouse Reclaim/Patrol"] = 0,
		["Mouse to Mexes"] = 0,
		["Move Window Position"] = 0,
		["Music Player"] = 0,
		NoDuplicateOrders = 65,
		OnlyFightersPatrol = 0,
		Options = 117,
		Outline = 12345,
		["Passive builders"] = 66,
		["Pause Screen"] = 14,
		["Pause/Unpause sounds"] = 0,
		["Persistent Build Spacing"] = 67,
		["Player Color Palette"] = 11,
		["Player-TV"] = 31,
		["Point Tracker"] = 0,
		Prospector = 94,
		["Quick Unload"] = 0,
		["Rank Icons"] = 105,
		ReclaimInfo = 68,
		["Red Build/Order Menu"] = 69,
		["Red Console (Battle and autohosts)"] = 70,
		["Red Console (In-game chat only)"] = 71,
		["Red Minimap"] = 23,
		["Red Tooltip"] = 17,
		Red_Drawing = 118,
		Red_UI_Framework = 5,
		RelativeMinimap = 72,
		["Resurrection Halos"] = 20,
		["Select n Center!"] = 110,
		["Selected Units Buttons"] = 73,
		["Self-Destruct icons"] = 21,
		["Set fighters on Fly mode"] = 106,
		["Set target default"] = 0,
		["Shadow Quality Manager"] = 12,
		["Share Tracker"] = 74,
		["Show Builder Queue"] = 0,
		["Show Orders"] = 75,
		["Smart Area Reclaim"] = 76,
		SmartNanos = 0,
		SmartSelect = 77,
		SmoothScroll = 0,
		Snow = 22,
		["Specific Unit Loader"] = 78,
		["Specific Unit Reclaimer"] = 79,
		["Spectate Selected"] = 80,
		["Spy move/reclaim defaults"] = 1,
		["State Prefs"] = 0,
		["State Remover"] = 0,
		["State Reverse Toggle"] = 81,
		["Statistics Collection"] = 82,
		["Stockpiler (dynamic)"] = 83,
		["Stop means Stop"] = 84,
		["Take Proxy"] = 85,
		TeamPlatter = 0,
		TeamStats = 10,
		Tombstones = 109,
		Tooltip = 4,
		["Top Bar"] = 6,
		["Transport AI"] = 0,
		["Transporter 2"] = 0,
		Transporting = 0,
		["Under construction gfx"] = 110,
		["Unit Finished Sounds"] = 86,
		["Unit Marker"] = 0,
		["Unit Mover"] = 0,
		["Unit Stats"] = 3,
		["Voice Notifs"] = 107,
		["Volume OSD"] = 87,
		["Vote interface"] = 13,
		["Waypoint Dragger"] = 108,
		["Widget Profiler"] = 0,
		["Widget Selector"] = 2,
		["Z Selector"] = 0,
		gui_transport_weight_limit = 88,
		["replay buttons"] = 12345,
	},
}
