return {
	armaca = {
		acceleration = 0.07,
		blocking = false,
		brakerate = 0.4275,
		buildcostenergy = 12000,
		buildcostmetal = 280,
		builddistance = 136,
		builder = true,
		buildpic = "ARMACA.DDS",
		buildtime = 17763,
		canfly = true,
		canmove = true,
		category = "ALL NOTLAND MOBILE NOTSUB VTOL NOWEAPON NOTSHIP NOTHOVER",
		collide = true,
		cruisealt = 80,
		description = "Tech Level 2",
		energymake = 10,
		energystorage = 50,
		energyuse = 10,
		explodeas = "smallExplosionGeneric-builder",
		footprintx = 2,
		footprintz = 2,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 180,
		maxslope = 10,
		maxvelocity = 6.4,
		maxwaterdepth = 0,
		metalmake = 0.1,
		metalstorage = 50,
		name = "Field Engineering Aircraft",
		objectname = "ARMACA",
		radardistance = 50,
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 383.5,
		terraformspeed = 650,
		turninplaceanglelimit = 360,
		turnrate = 240,
		workertime = 100,
		buildoptions = {
			[1] = "armsolar",
			[2] = "armwin",
			[3] = "armgeo",
			[4] = "armmex",
			[5] = "armamex",
			[6] = "armmakr",
			[7] = "armnanotc",
			[8] = "armeyes",
			[9] = "armarad",
			[10] = "armdrag",
			[11] = "armclaw",
			[12] = "armllt",
			[13] = "armbeamer",
			[14] = "armhlt",
			[15] = "armguard",
			[16] = "armrl",
			[17] = "armmpacko",
			[18] = "armsd",
			[19] = "armdl",
			[20] = "armjamt",
			[21] = "armflak",
			[22] = "armgate",
			[23] = "armmlv",
			[24] = "armck",
			[25] = "armack",
			[26] = "armpw",
			[27] = "armvader",
			[28] = "armspy",
			[29] = "armmercury",
			[30] = "armfdrag",
		},
		customparams = {
			area_mex_def = "armmex",
			model_author = "FireStorm",
			subfolder = "armaircraft/t2",
			techlevel = 2,
			wingsurface = 0.25,
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3-builder",
				[2] = "deathceg4-builder",
				[3] = "deathceg2-builder",
			},
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolarmv",
			},
			select = {
				[1] = "vtolarac",
			},
		},
	},
}
