local armorDefs = {
	commanders = {
		"armcom",
		"armdecom",
		"corcom",
		"cordecom",
	},
	indestructable = {
		"xmasball",
		"xmasball2",
		"armstone",
		"corstone",
		"dice",
		"chip",
	},
	crawlingbombs = {
		"armvader",
		"corroach",
		"corsktl",
	},
	["else"] = {
		
		"armaak",
		"armack",
		
		"armah",
		
		"armamph",
		
		
		"armch",
		"armck",
		
		"armcv",
		
		
		
		"armfark",
		"armfast",
		"armfatf",
		"armfav",
		
		"armfido",
		"armflea",
		
		
		"armjeth",

		
		"armmart",
		"armmav",
		"armmerl",		
		"armmh",		
		"armpb",		
		"armpw",
		"armrectr",		
		"armrock",
		"armsam",
		"armscab",		
		"armsh",
		"armsnipe",		
		"armspid",
		"armsptk",
		"armthovr",
		"armzeus",
		"armamsub",
		"armconsul",
		"coraak",
		"corack",
		"coracv",
		"corah",
		"corak",
		"corch",
		"corck",
		"corcrash",
		"corcv",
		"corfast",
		"corfatf",
		"corfav",
		"corhrk",
		"cormabm",		
		"cormart",		
		"cormh",
		"cormist",		
		"cormort",		
		"cornecro",
		"corstorm",
		"cortermite",
		"corthovr",
		"corthud",
		"corvroc",
		"corwolv",
		"coramsub",	
		"corhal",
		"armart",
    	"armbeaver",
		"coramph",
		"cormuskrat",
		"corseal",
        "armwar",
        "armspy",
		"cormando",
		"corspy",
        "armmlv",
		"cormlv",
		"corpyro",
		"armaser",
		"armjam",		
		"armmark",
		"armseer",	
		"coreter",		
		"corspec",
		"corvoyr",
		"corvrad",				
		"cortrem",		
		"corsh",
		"armflash",	-- light tanks are too small to be considered proper "tanks" - they take damage as though regular vehicles
		"corgator",
	},
	
	tanks =
	{
		"armyork",
		"corlevlr",
		"armbull",
		"armfboy", -- yes, FatBoy is too a tank, a big fat walking tank
		"corgol",
		"corsumo",		
		"corraid",
		"correap",
		"corsnap",
		"armcroc",
		"armpincer",	
		"corparrow",
		"corintr",
		"corgarp",
		"armst",
		"corban",
		"armstump",
		"corcan",
		"armlatnk",
		"armjanus",
		"armanac",
	},
	
	exp = 
	{	
		"armbanth",
		"corcat",
		"armraz",
		"armvang",
		"corkarg",
		"corkrog",
		"corjugg",
		"corshiva",
		"armmar",
	},
	
	buildings =
	{	
		"armjuno",
		"armageo","armacv",
		"armadvsol","armamex","armap",
		"armasp",
		"armbrtha","armclaw","armdrag",
		"armemp","armdf",
	
		"armmanni",
		"armlab","armllt","armmakr","armmex",
		"armrl","armsd","armsolar","armsy","armplat","armmmkr",
		"armmoho",
		"armmstor",
		"armtarg","armtide",
		"armuwes",
		"armuwfus",
		"armomex",
		"armuwmex",
		"armuwmme",
		"armuwmmm",
		"armuwms",
		
		"armwin",
		"corbhmth",
		"cortarg",
		"corint",
		"corplat",
		"corason",
		"armason",
		"corasp","corbuzz","corap","cordrag",
		"corestor","corageo","corjuno","armvp",
		"armvulc","coradvsol",
		"corfdrag",
		"corfhp",
		"corfmkr",
		"corhlt",
		"corhp","cormstor","cormakr",
		"corvp",
		"armafus",
		"armaap",
		"armalab",
		"armamd",
		"corsy","armasy",
		"armavp","armckfus",
		"corlab",
		"corllt","cormaw",
		"cormex","cormmkr",
		"cormoho",
		"corrl",
		"corsd","corsolar","corgeo","corfort","corfrt","corfhlt",
		"cortide","cortron",
		"coruwes",
		"coruwfus",
		"coromex",
		"coruwmex",
		"coruwmme",
		"coruwmmm",
		"coruwms",
		"corvipe",	"corwin",
		"armdl",
		"cordl", "armfflak",
		"armflak","corenaa",
		"corflak",
		"corsent","corexp","armpacko","cormadsam","corscreamer",
		"armbeamer","corhllt",
		"armmercury","cormexp",
		"coreyes",
		"corfrad",
		"armfmkr",
		"armfort",
		"armfrt",
		"armgeo",
		"armgmm",
		"armham",
		"armhlt",
		"armhp","armfdrag",
		"armestor",		"armfhlt",
		"armfhp",
		"corjamt",
		"corrad",
		"corshroud",
		"corsonar",
		"corsilo",
		"armamb",
		"armguard",
		"corpun",
		"cortoast",
		"armanni",
		"cordoom",
		"armtl",
		"cortl",
		"armatl",
		"coratl",
		"armcir",
		"armuwadves",
		"armuwadvms",
		"corerad",
		"coruwadves",
		"coruwadvms",
		"armfus",
		"armshltx",
		"armsilo",
		"corafus",
		"coraap",
		"coralab",
		"corasy",
		"coravp",
		"corfmd",
		"corfus",
		"corgant",
		"armrad",
		"armveil",
		"armsonar",
		"corarad",
		"armeyes",
		"armfrad",
		"armjamt", 
		"armarad",
	},

	
	bombers = {
		"chickenf1",
		"chickenf1b",
		"chickenf2",
		"armthund",
		"corshad",
		"armliche",
		"armlance",
		"armpnix",
		"armsb",
		"armstil",
		"corhurc",
		"corsb",
		"cortitan",
	},
	fighters = {
		"chickenw1",
		"chickenw1b",
		"chickenw1c",
		"chickenw1d",
		"chickenw2",
		"armfig",
		"corveng",
		"armhawk",
		"armsfig",
		"corsfig",
		"corvamp",
	},
	mines = {
		"armfmine3",
		"armmine1",
		"armmine2",
		"armmine3",
		"corfmine3",
		"cormine1",
		"cormine2",
		"cormine3",
		"cormine4",
	},
	nanos = {
		"armnanotc",
		"cornanotc",
		"armnanotcplat",
		"cornanotcplat",
	},
	vtol = {
		"chickens3",
		"armaca",
		"armca",
		"armcsa",
		"armdfly",
		"armpeep",
		"armseap",
		"corseah",
		"coraca",
		"corca",
		"corcsa",
		"corfink",
		"corseap",
        "armawac",
		"armsehak",
		"corawac",
		"corhunt",
        "armatlas",
		"corvalk",
        "armbrawl",
		"armkam",
		"armsaber",
        "armblade",
		"corbw",
		"corape",
		"corcrw",
		"corcut",
		"corfalchion",
		"armsword",
	},
	shields = {
		"armgate",
		"corgate",
		--"armfgate", Not currently used by BA
		--"corfgate", Not currently used by BA
	},
	lboats = {
		"corpt",
		"armpt",
		"armpship",
		"corpship",
		"armcs",
		"armmls",
		"armsjam",
		"corcs",
		"coresupp",
		"cormls",
		"armdecade",
		"corsjam",
	},

	hvyboats = {
		"armroy",
		"corroy",
		"corarch",
		"armaas",
		"armcrus",
		"armmship",
		"corcrus",
		"cormship",
		"armcarry",
		"corcarry",
		"armtship",
		"cortship",
		"armbats",
		"corbats",
		"armepoch",
		"corblackhy",
	},
		
	subs = {
		"armsub",
		"corsub",
        "armsubk",
		"corshark",
        "corssub",
		"armserp",
		"armacsub",
        "coracsub",
		"armrecl",
		"correcl",
	},
	

	tinychicken =
	{
		"chicken_dodo1",
		"chickenh1",
		"chickenh1b",
	},
	chicken =
	{
		"ve_chickenq",
		"e_chickenq",
		"n_chickenq",
		"h_chickenq",
		"vh_chickenq",
		"epic_chickenq",
		"chicken1",
		"chicken1b",
		"chicken1c",
		"chicken1d",
		"chicken1x",
		"chicken1y",
		"chicken1z",
		"chicken2",
		"chicken2b",
		"chicken_dodo2",
		"chickena1",
		"chickena1b",
		"chickena1c",
		"chickena2",
		"chickena2b",
		"chickenc1",
		"chickenc2",
		"chickenc3",
		"chickenc3b",
		"chickenc3c",
		"chickend1",
		"chickenr1",
		"chickenr2",
		"chickenh2",
		"chickenh3",
		"chickenh4",
		"chickenh5",
		"chickenr3",
		"chickens1",
		"chickens2",
		"chickenp1",
		"roost",
	},
}

-- add BAR variants
if Game and Game.gameVersion and (string.find(Game.gameVersion, 'test') or string.find(Game.gameVersion, '$VERSION')) then
	function tableMerge(t1, t2)
		for k,v in pairs(t2) do if type(v) == "table" then if type(t1[k] or false) == "table" then tableMerge(t1[k] or {}, t2[k] or {}) else t1[k] = v end else t1[k] = v end end
		return t1
	end
	local armorDefsBar = {}
	for category,names in pairs(armorDefs) do
		local catkeycount = #names
		for _,name in pairs(names) do
			if armorDefsBar[category] == nil then
				armorDefsBar[category] = {}
			end
			catkeycount = catkeycount + 1
			armorDefsBar[category][catkeycount] = name..'_bar'
		end
	end
	armorDefs = tableMerge(armorDefs, armorDefsBar)
end

return armorDefs
