ArmDefsBuildOptions = 
{
			"armsolar",
			"armadvsol",
			"armwin",			
			"armgeo",
			"armfus",
			"armmstor",
			"armestor",
			"armmex",
			"armmoho",			
			"armmakr",
			"armlab",
			"armalab",
			"armvp",
			"armavp",
			"armap",
			"armaap",
			"armhp",			
			"armnanotc",
			"armasp",
			"armeyes",			
			"armrad",
			"armarad",
			"armjamt",
			"armdrag",
			"armfort",			
			"armllt",
			"armhlt",
			"armguard",
			"armbeamer",
			"armpacko",
			"armmercury",
			"armpb",
			"armrl",
			"armflak",
			"armamd",
			"armveil",
			"armgate",
			"armsd",
			"armbrtha",
			"armdl",			
			"armtide",
			"armuwms",
			"armuwes",
			"armuwmex",
			"armfmkr",
			"armsy",
			"armasy",
			"armfhp",
			"armplat",
			"armamsub",
			"armnanotcplat",					
			"armfdrag",	
			"armtl",
			"armatl",
			"armfrt",
			"armfflak",
			"armfrad",
			"armuwmme",
			-- MOBILE UNITS
			"armck",
			"armack",
			"armcv",
			"armacv",
			"armca",
			"armaca",
			"armatlas",
			"armdfly",
			"armawac",
			"armpw",
			"armrectr",
			"armpeep",
			"armfav",
			"armmlv",
			"armvader",
			"armspy",
			"armmav",
			"armfboy",
			"armsnipe",
			-- MINES
			"armmine1",
			"armmine2",
			"armmine3",
			"armfmine3",
}

ArmBuildOptions = 
{
			armsolar= 1,
			armadvsol= 3,
			armwin= 1,			
			armgeo= 3,
			armfus=6,
			armmstor= 1,
			armestor= 1,
			armmex= 1,
			armmoho= 4,			
			armmakr= 1,
			armlab= 1,
			armalab = 4,
			armvp= 1,
			armavp= 3,
			armap= 1,
			armaap=4,
			armhp= 3,			
			armnanotc= 1,
			armasp = 3,
			armnanotcplat= 2,			
			armeyes= 1,
			armrad= 1,
			armarad=4,
			armjamt = 2,
			armdrag= 1,
			armfort= 5,			
			armllt= 1,
			armhlt=2,
			armguard=3,
			armbeamer = 3,
			armpacko = 4,
			armmercury = 5,
			armpb= 5,
			armrl= 1,
			armflak= 3,
			armamd = 6,
			armveil = 4,
			armgate = 5,
			armsd = 4,
			armbrtha = 6,
			armdl= 1,			
			armtide= 1,
			armuwms= 1,
			armuwes= 1,
			armuwmex= 1,
			armuwmme= 4,
			armfmkr= 1,
			armsy= 1,
			armasy= 3,
			armfhp= 3,
			armplat= 3,
			armamsub= 3,	
			armfdrag= 1,	
			armtl= 1,
			armatl= 5,
			armfrt= 1,
			armfflak= 5,
			armfrad= 1,
			-- MOBILE UNITS
			armck = 1,
			armack = 4,
			armca = 1,
			armaca = 4,
			armcv = 1,
			armacv = 4,
			armatlas = 1,
			armdfly = 4,
			armawac = 5,
			armpw = 1,
			armrectr = 1,
			armpeep = 1,
			armfav = 1,
			armmlv = 1,
			armvader = 3,
			armspy = 4,
			armmav = 5,
			armfboy = 6,
			armsnipe = 6,
			-- MINES
			armmine1 = 1,
			armmine2 = 2,
			armmine3 = 3,
			armfmine3 = 3,
}
ArmBuildOptionsStop = 
{

}
CoreDefsBuildOptions = 
{
			"corsolar",
			"coradvsol",
			"corwin",			
			"corgeo",
			"corfus",
			"cormstor",
			"corestor",
			"cormex",
			"cormoho",	
			"cormakr",
			"corlab",
			"coralab",
			"corvp",
			"corap",
			"coraap",
			"corasp",
			"corhp",			
			"cornanotc",
			"coreyes",			
			"corrad",
			"corarad",
			"cordrag",
			"corfort",	
			"corjamt",
			"corllt",
			"corhlt",
			"corhllt",
			"corpun",
			"cormadsam",
			"corscreamer",
			"corvipe",
			"corrl",
			"corflak",
			"corfmd",
			"corshroud",
			"corsd",
			"corint",
			"corgate",
			"cordl",			
			"cortide",
			"coruwms",
			"coruwes",
			"coruwmex",
			"corfmkr",
			"corsy",
			"corasy",
			"corfhp",
			"corplat",
			"coramsub",	
			"cornanotcplat",			
			"corfdrag",	
			"cortl",
			"coratl",
			"corfrt",
			"corenaa",
			"corfrad",
			"coruwmme",
			-- MOBILE UNITS
			"corck",
			"corack",
			"corcv",
			"coracv",
			"corca",
			"coraca",
			"corvalk",
			"corseah",
			"corawac",
			"corak",
			"cornecro",
			"corfink",
			"corfav",
			"cormlv",
			"corroach",
			"corspy",
			"cormando",
			"corhrk",
			"corsumo",
			-- MINES
			"cormine1",
			"cormine2",
			"cormine3",
			"corfmine3",

}
CoreBuildOptions = 
{
			corsolar = 1 ,
			coradvsol = 3 ,
			corwin = 1,			
			corgeo = 3,
			corfus = 6,
			cormstor = 1,
			corestor = 1,
			cormex = 1,
			cormoho = 4,	
			cormakr = 1,
			corlab = 1,
			coralab = 3,
			corvp = 1,
			corap = 1,
			coraap=4,
			corasp=3,
			corhp = 3,			
			cornanotc = 1,
			cornanotcplat = 2,			
			coreyes = 1,			
			corrad = 1,
			corarad = 4,
			cordrag = 1,
			corfort = 5,	
			corjamt = 2,
			corllt = 1,
			corhlt = 2,
			corhllt = 3,
			corpun = 3,
			cormadsam = 4,
			corscreamer = 5,
			corvipe = 5,
			corrl = 1,
			corflak = 3,
			corfmd = 6,
			corshroud = 4,
			corsd = 4,
			corgate = 5,
			corint = 6,
			cordl = 1,			
			cortide = 1,
			coruwms = 1,
			coruwes = 1,
			coruwmex = 1,
			corfmkr = 1,
			corsy = 1,
			corasy = 3,
			corfhp = 3,
			corplat = 3,
			coramsub = 3,	
			corfdrag = 1,	
			cortl = 1,
			coratl = 5,
			corfrt = 1,
			corenaa = 5,
			corfrad = 1,
			coruwmme = 4,
			-- MOBILE UNITS
			corck = 1,
			corack = 4,
			corcv = 1,
			coracv = 4,
			corca = 1,
			coraca = 4,
			corvalk = 1,
			corseah = 4,
			corawac = 5,
			corak = 1,
			cornecro = 1,
			corfink = 1,
			corfav = 1,
			cormlv = 1,
			corroach = 3,
			corspy = 4,
			cormando = 5,
			corhrk = 6,
			corsumo = 6,
			-- MINES
			cormine1 = 1,
			cormine2 = 2,
			cormine3 = 3,
			corfmine3 = 3,
}
CoreBuildOptionsStop = 
{

}
armlevel1buildoptions = {
			"armsolar",
			"armwin",
			"armmstor",
			"armestor",
			"armmex",
			"armmakr",
			"armlab",
			"armvp",
			"armap",
			"armeyes",
			"armrad",
			"armdrag",
			"armllt",
			"armrl",
			"armdl",
			"armtide",
			"armuwms",
			"armuwes",
			"armuwmex",
			"armfmkr",
			"armsy",
			"armfdrag",
			"armtl",
			"armfrt",
			"armfrad",
			"armck",
			"armcv",
			"armca",
			"armatlas",
			"armpw",
			"armrect",
			"armpeep",
			"armfav",
}
corlevel1buildoptions = {
			"corsolar",
			"corwin",
			"cormstor",
			"corestor",
			"cormex",
			"cormakr",
			"corlab",
			"corvp",
			"corap",
			"coreyes",
			"corrad",
			"cordrag",
			"corllt",
			"corrl",
			"cordl",
			"cortide",
			"coruwms",
			"coruwes",
			"coruwmex",
			"corfmkr",
			"corsy",
			"corfdrag",
			"cortl",
			"corfrt",
			"corfrad",
			"corck",
			"corcv",
			"corca",
			"corvalk",
			"corak",
			"cornecro",
			"corfink",
			"corfav",
}
