return {
	corca = {
		acceleration = 0.06,
		blocking = false,
		brakerate = 0.4275,
		buildcostenergy = 48000,
		buildcostmetal = 150,
		builddistance = 136,
		builder = true,
		buildpic = "CORCA.DDS",
		buildtime = 3557,
		canfly = true,
		canmove = true,
		category = "ALL MOBILE NOTLAND NOTSUB VTOL NOWEAPON NOTSHIP NOTHOVER",
		collide = true,
		cruisealt = 75,
		description = "Tech Level 1",
		energymake = 5,
		energystorage = 25,
		energyuse = 5,
		explodeas = "smallexplosiongeneric",
		footprintx = 3,
		footprintz = 3,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 145,
		maxslope = 10,
		maxvelocity = 6.7,
		maxwaterdepth = 0,
		metalmake = 0.05,
		metalstorage = 25,
		name = "Service Aircraft",
		objectname = "CORCA",
		radardistance = 50,
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd",
		sightdistance = 351,
		terraformspeed = 225,
		turninplaceanglelimit = 360,
		turnrate = 240,
		workertime = 70,
		buildoptions = {
			[1] = "corsolar",
			[2] = "corwin",
			[3] = "cormex",
			[5] = "cornanotc",
			[6] = "coreyes",
			[7] = "cordrag",
			[8] = "cormaw",
			[9] = "corllt",
			[10] = "corrl",
			[11] = "corrad",
			[12] = "cordl",
			[13] = "corjamt",
			[14] = "cormine1",
			[15] = "cormine2",
			[16] = "corfdrag",
		},
		customparams = {
			area_mex_def = "cormex",
			description_long = "A Service Aircraft is a self-contained combat engineering platform, capable of light construction duty and regular maintenance jobs. Warranty voids if exposed to enemy fire.",
			model_author = "Mr Bob",
			subfolder = "coreaircraft",
			wingsurface = 0.5,
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2-builder",
				[2] = "deathceg3-builder",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
	},
}
