return {
	coraca = {
		acceleration = 0.065,
		blocking = false,
		brakerate = 0.4275,
		buildcostenergy = 11000,
		buildcostmetal = 300,
		builddistance = 136,
		builder = true,
		buildpic = "CORACA.DDS",
		buildtime = 18001,
		canfly = true,
		canmove = true,
		category = "ALL NOTLAND MOBILE NOTSUB VTOL NOWEAPON NOTSHIP NOTHOVER",
		collide = true,
		cruisealt = 70,
		description = "Tech Level 2",
		energymake = 10,
		energystorage = 50,
		energyuse = 10,
		explodeas = "smallexplosiongeneric-builder",
		footprintx = 2,
		footprintz = 2,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 185,
		maxslope = 10,
		maxvelocity = 6.05,
		maxwaterdepth = 0,
		metalmake = 0.1,
		metalstorage = 50,
		name = "Forward Operations Aircraft",
		objectname = "CORACA",
		radardistance = 50,
		seismicsignature = 0,
		selfdestructas = "smallExplosionGenericSelfd-builder",
		sightdistance = 383.5,
		terraformspeed = 650,
		turninplaceanglelimit = 360,
		turnrate = 240,
		workertime = 100,
		buildoptions = {
			[1] = "corsolar",
			[2] = "corwin",
			[3] = "corgeo",
			[4] = "cormex",
			[5] = "corexp",
			[6] = "cormakr",
			[7] = "cornanotc",
			[8] = "coreyes",
			[9] = "corarad",
			[10] = "cordrag",
			[11] = "cormaw",
			[12] = "corllt",
			[13] = "corhllt",
			[14] = "corhlt",
			[15] = "corpun",
			[16] = "corrl",
			[17] = "cormadsam",
			[18] = "corvipe",
			[19] = "cordl",
			[20] = "corjamt",
			[21] = "corflak",
			[22] = "corgate",
			[23] = "cormlv",
			[24] = "corck",
			[25] = "corack",
			[26] = "corak",
			[27] = "cormando",
			[28] = "corsd",
			[29] = "corfdrag",
			[30] = "corscreamer",
		},
		customparams = {
			area_mex_def = "cormex",
			model_author = "Mr Bob",
			subfolder = "coreaircraft/t2",
			techlevel = 2,
			wingsurface = 0.7,
		},
		sfxtypes = {
			crashexplosiongenerators = {
				[1] = "crashing-small",
				[2] = "crashing-small",
				[3] = "crashing-small2",
				[4] = "crashing-small3",
				[5] = "crashing-small3",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3-builder",
				[2] = "deathceg4-builder",
				[3] = "deathceg2-builder",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
	},
}
